Repository OnTheTop/ott-android, pull requests merged in 2022-03, with the labels that each got.

#1 Feature/project base
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/unithon/ott/App.kt
  app/src/main/java/com/unithon/ott/common/base/BaseActivity.kt
  app/src/main/java/com/unithon/ott/common/base/BaseDialog.kt
  app/src/main/java/com/unithon/ott/common/base/BaseFragment.kt
  app/src/main/java/com/unithon/ott/common/network/RetrofitClient.kt
  app/src/main/java/com/unithon/ott/data/local/SharedPreference.kt
  app/src/main/java/com/unithon/ott/data/model/model.md
  app/src/main/java/com/unithon/ott/data/remote/api/api.md
  app/src/main/java/com/unithon/ott/data/remote/datasource/datasource.md
  app/src/main/java/com/unithon/ott/data/remote/response/response.md
  app/src/main/java/com/unithon/ott/data/repository/repository.md
  app/src/main/java/com/unithon/ott/domain/repository/repository.md
  app/src/main/java/com/unithon/ott/presentation/adapter/BindingAdapter.kt
  app/src/main/java/com/unithon/ott/presentation/ui/MainActivity.kt
  app/src/main/java/com/unithon/ott/presentation/ui/dialog/LoadingDialog.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_loading.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: feature

#3 [Doc] 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#2 [Feat] 깃허브 cicd 추가
  .github/workflows/android.yml
Labels: feature

#4 PR 템플릿 추가
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#8 패키지 구조 및 공통 앱바
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/unithon/ott/presentation/ui/album/AlbumActivity.kt
  app/src/main/java/com/unithon/ott/presentation/ui/album/AlbumViewModel.kt
  app/src/main/java/com/unithon/ott/presentation/ui/home/HomeActivity.kt
  app/src/main/java/com/unithon/ott/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/unithon/ott/presentation/ui/question/QuestionActivity.kt
  app/src/main/java/com/unithon/ott/presentation/ui/question/QuestionViewModel.kt
  app/src/main/res/drawable/ic_arrow_back.xml
  app/src/main/res/layout/activity_album.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_question.xml
  app/src/main/res/layout/appbar.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature, 준영

#10 사진 미션 이미지 불러오기
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/unithon/ott/common/utils/Commontype.kt
  app/src/main/java/com/unithon/ott/presentation/ui/photo/PhotoMissionActivity.kt
  app/src/main/java/com/unithon/ott/presentation/ui/photo/PhotoMissionViewModel.kt
  app/src/main/res/layout/activiy_photo_mission.xml
  app/src/main/res/layout/appbar.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature, 재원

#12 홈 기본 디자인
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/unithon/ott/presentation/ui/album/AlbumActivity.kt
  app/src/main/java/com/unithon/ott/presentation/ui/history/HistoryActivity.kt
  app/src/main/java/com/unithon/ott/presentation/ui/history/HistoryViewModel.kt
  app/src/main/java/com/unithon/ott/presentation/ui/home/HomeActivity.kt
  app/src/main/java/com/unithon/ott/presentation/ui/question/QuestionActivity.kt
  app/src/main/res/drawable/ic_bbibbi.xml
  app/src/main/res/drawable/ic_menu.xml
  app/src/main/res/drawable/ic_small_bbibbi.xml
  app/src/main/res/drawable/ic_speech_bubble.xml
  app/src/main/res/layout/activity_history.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/bbibbi.xml
  app/src/main/res/values/strings.xml
Labels: feature, design

#16 사진 미션 디자인
  app/src/main/java/com/unithon/ott/presentation/ui/photo/PhotoMissionViewModel.kt
  app/src/main/res/drawable/bg_photo_comment.xml
  app/src/main/res/drawable/ic_arrow_back.xml
  app/src/main/res/drawable/ic_mission_bubble.xml
  app/src/main/res/drawable/ic_upload_image.xml
  app/src/main/res/layout/activiy_photo_mission.xml
  app/src/main/res/layout/appbar.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/font_style.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: design, 재원

#20 히스토리 화면 구성
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/unithon/ott/presentation/adapter/HistoryTabAdapter.kt
  app/src/main/java/com/unithon/ott/presentation/ui/history/AlbumFragment.kt
  app/src/main/java/com/unithon/ott/presentation/ui/history/HistoryActivity.kt
  app/src/main/java/com/unithon/ott/presentation/ui/history/MissionFragment.kt
  app/src/main/res/drawable/bg_history_graph.xml
  app/src/main/res/drawable/bg_history_love_graph.xml
  app/src/main/res/drawable/bg_history_total_graph.xml
  app/src/main/res/drawable/ic_dropdown.xml
  app/src/main/res/drawable/ic_history_close.xml
  app/src/main/res/layout/activity_history.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/appbar.xml
  app/src/main/res/layout/bbibbi.xml
  app/src/main/res/layout/fragment_album.xml
  app/src/main/res/layout/fragment_mission.xml
  app/src/main/res/values/font_style.xml
  app/src/main/res/values/strings.xml
Labels: feature, design, 준영

#23 질문 미션 화면
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/unithon/ott/presentation/ui/photo/PhotoMissionActivity.kt
  app/src/main/java/com/unithon/ott/presentation/ui/question/QuestionActivity.kt
  app/src/main/java/com/unithon/ott/presentation/ui/question/QuestionWriteActivity.kt
  app/src/main/java/com/unithon/ott/presentation/ui/question/QuestionWriteViewModel.kt
  app/src/main/res/drawable-v24/bg_question_answer.xml
  app/src/main/res/drawable/ic_photo_bubble.xml
  app/src/main/res/drawable/ic_question_bubble.xml
  app/src/main/res/layout/activity_question.xml
  app/src/main/res/layout/activity_write_question.xml
  app/src/main/res/layout/activiy_photo_mission.xml
  app/src/main/res/layout/item_question_mission.xml
  app/src/main/res/values/strings.xml
Labels: bug, design, 재원

#27 미션 상태 로컬 디비 저장
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/unithon/ott/data/local/LocalDataSource.kt
  app/src/main/java/com/unithon/ott/data/local/SharedPreference.kt
  app/src/main/java/com/unithon/ott/data/repository/MissionRepositoryImpl.kt
  app/src/main/java/com/unithon/ott/data/repository/repository.md
  app/src/main/java/com/unithon/ott/domain/repository/MissionRepository.kt
  app/src/main/java/com/unithon/ott/domain/repository/repository.md
  app/src/main/java/com/unithon/ott/presentation/ui/MainActivity.kt
  app/src/main/java/com/unithon/ott/presentation/ui/home/HomeActivity.kt
  app/src/main/java/com/unithon/ott/presentation/ui/home/HomeViewModel.kt
  app/src/main/res/drawable/ic_first_bbibbi.xml
  app/src/main/res/drawable/ic_white_close.xml
  app/src/main/res/layout/activity_history.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: improve, feature, design, 준영

#31 가족 생성하기 api 연동
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/unithon/ott/common/network/RetrofitClient.kt
  app/src/main/java/com/unithon/ott/data/local/LocalDataSource.kt
  app/src/main/java/com/unithon/ott/data/local/SharedPreference.kt
  app/src/main/java/com/unithon/ott/data/model/FamilyModel.kt
  app/src/main/java/com/unithon/ott/data/model/model.md
  app/src/main/java/com/unithon/ott/data/remote/api/FamilyService.kt
  app/src/main/java/com/unithon/ott/data/remote/api/api.md
  app/src/main/java/com/unithon/ott/data/remote/datasource/FamilyDatasource.kt
  app/src/main/java/com/unithon/ott/data/remote/datasource/datasource.md
  app/src/main/java/com/unithon/ott/data/remote/response/FamilyResponse.kt
  app/src/main/java/com/unithon/ott/data/remote/response/response.md
  app/src/main/java/com/unithon/ott/data/repository/FamilyRepository.kt
  app/src/main/java/com/unithon/ott/domain/repository/FamilyRepository.kt
  app/src/main/java/com/unithon/ott/presentation/ui/onboarding/StartActivity.kt
  app/src/main/java/com/unithon/ott/presentation/ui/onboarding/StartFragment3.kt
  app/src/main/java/com/unithon/ott/presentation/ui/onboarding/StartFragment4.kt
  app/src/main/java/com/unithon/ott/presentation/ui/onboarding/StartViewModel.kt
  app/src/main/java/com/unithon/ott/presentation/ui/onboarding/enter/EnterFragment2.kt
  app/src/main/res/layout/fragment_enter_first.xml
  app/src/main/res/layout/fragment_enter_second.xml
  app/src/main/res/layout/fragment_start_fourth.xml
  app/src/main/res/layout/fragment_start_second.xml
  app/src/main/res/layout/fragment_start_third.xml
  app/src/main/res/values/strings.xml
Labels: feature, server, 재원

#30 히스토리 미션 모음
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/unithon/ott/data/model/Mission.kt
  app/src/main/java/com/unithon/ott/data/remote/api/MissionService.kt
  app/src/main/java/com/unithon/ott/data/remote/datasource/MissionDatasource.kt
  app/src/main/java/com/unithon/ott/data/remote/response/MissionListResponse.kt
  app/src/main/java/com/unithon/ott/data/repository/MissionRepositoryImpl.kt
  app/src/main/java/com/unithon/ott/domain/repository/MissionRepository.kt
  app/src/main/java/com/unithon/ott/presentation/adapter/BindingAdapter.kt
  app/src/main/java/com/unithon/ott/presentation/adapter/MissionListAdapter.kt
  app/src/main/java/com/unithon/ott/presentation/ui/history/HistoryActivity.kt
  app/src/main/java/com/unithon/ott/presentation/ui/history/HistoryViewModel.kt
  app/src/main/java/com/unithon/ott/presentation/ui/history/MissionFragment.kt
  app/src/main/java/com/unithon/ott/presentation/ui/home/HomeActivity.kt
  app/src/main/res/layout/activity_history.xml
  app/src/main/res/layout/bbibbi.xml
  app/src/main/res/layout/fragment_mission.xml
  app/src/main/res/values/strings.xml
Labels: feature, server, 준영

#35 질문 조회하기 api
  app/src/main/java/com/unithon/ott/data/remote/api/QuestionService.kt
  app/src/main/java/com/unithon/ott/data/remote/datasource/QuestionDataSource.kt
  app/src/main/java/com/unithon/ott/data/remote/response/MissionResponse.kt
  app/src/main/java/com/unithon/ott/data/repository/QuestionRepository.kt
  app/src/main/java/com/unithon/ott/domain/repository/QuestionRepository.kt
  app/src/main/java/com/unithon/ott/presentation/ui/home/HomeActivity.kt
  app/src/main/java/com/unithon/ott/presentation/ui/question/QuestionActivity.kt
  app/src/main/java/com/unithon/ott/presentation/ui/question/QuestionViewModel.kt
  app/src/main/res/layout/activity_question.xml
Labels: feature, 재원

#36 삐삐 미션 제공
  .idea/misc.xml
  app/src/main/java/com/unithon/ott/data/remote/api/MissionService.kt
  app/src/main/java/com/unithon/ott/data/remote/datasource/MissionDatasource.kt
  app/src/main/java/com/unithon/ott/data/remote/response/CurMissionResponse.kt
  app/src/main/java/com/unithon/ott/data/repository/MissionRepositoryImpl.kt
  app/src/main/java/com/unithon/ott/domain/repository/MissionRepository.kt
  app/src/main/java/com/unithon/ott/presentation/adapter/HistoryTabAdapter.kt
  app/src/main/java/com/unithon/ott/presentation/ui/history/AlbumFragment.kt
  app/src/main/java/com/unithon/ott/presentation/ui/home/HomeActivity.kt
  app/src/main/java/com/unithon/ott/presentation/ui/home/HomeViewModel.kt
  app/src/main/res/drawable/new_pic.png
  app/src/main/res/drawable/old_pic.png
  app/src/main/res/layout/fragment_album.xml
  app/src/main/res/values/strings.xml
Labels: improve, feature, 준영
